# Generated by Django 4.1.7 on 2023-03-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('Science', 'Science'), ('Commercial', 'Commercial'), ('Historical', 'Historical'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('History', 'History'), ('Adventure', 'Adventure'), ('Cartoon', 'Cartoon'), ('Fairytale', 'Fairytale'), ('Alphabets', 'Alphabets')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=2000)),
                ('genre', models.CharField(max_length=200)),
                ('review', models.TextField(blank=True)),
                ('book_available', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default=False, max_length=2083)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
