# Generated by Django 4.1.7 on 2023-03-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
    ]
